#targets:
#  $default:
#    builders:
##     constructor:
##     change_notifier_sample|builder|constructorGenerator:
##      builder|constructorGenerator:
#      oop_extension|constructor_generator:
#        enabled: true


builders:
  constructor_generator:
    #    target: ":oop_extension"
    import: "package:dart_oop_extension/builder.dart"
    builder_factories: ["constructorGenerator"]
    # The `partId` argument to `SharedPartBuilder` is "some_cool_builder"
#    build_extensions: {".dart": [".g.part"]}

#    build_extensions: {".dart": ["g.dart"]}
#    build_extensions: {".dart": [".g.dart"]}
#    build_extensions: {".dart": [".gen.dart"]}

#    build_extensions: {}   # w/o errors; deleted existing file and do nothing
#    build_extensions: {".dart": []}
    build_extensions: {}


#    build_extensions:
#      .dart:
#        - .g.dart
    auto_apply: dependents
#    build_to: cache
    # To copy the `.g.part` content into `.g.dart` in the source tree
    applies_builders: ["source_gen|combining_builder"]


#targets:
#  $default:
#    builders: change_notifier_sample|builder|constructorGenerator
